Update version modal
sophiemoustard/alenvi-erp-mobile pull request #3
Opened 2021-04-08 09:41 UTC by cmolle

- [x] J'ai testé sur iphone
- [x] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que j'envoie un nouveau parametre de route

- [ ] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite: l'api sera en prod avant la mep de l'application mobile
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [ ] Je n'ai pas changé de constante -np

- J'ai ajouté une variable d'environnement : ajout des fichiers dans le dossier env
  - [x] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage : Lorsque j'ouvre l'application, si je n'ai plus une version maintenues, la modale de mise a jour s'affiche. Sinon j'ai une page blanche. 

Deux petits soucis que l'on a eu dans cette pr : 
- le useEffect n'a pas besoin de dependance dans son tableau. Il y a des elements de reponses dans cet article https://reacttraining.com/blog/when-to-use-functions-in-hooks-dependency-array/ . J'ai l'impression que React considere que `shouldUpdate` ne depend que de variables/fonctions qui ne sont pas modifiés entre deux rendus, et que du coup il ne changera pas non plus. 
- Dans environment.ts, il considere que l'import des fichiers d'env est un import avec extension. On n'a pas reussi a trouver pourquoi mais on a l'impression que ca vient du fait qu'on a mis environment.ts en typescript.

2021-04-08 12:33 UTC, sophiemoustard requested changes

2021-04-08 12:33 UTC, sophiemoustard commented on App/index.tsx
> +import Version from '../src/api/version';
je me dit qu'en suivant al logique de nommage, il faudrait nommer le fichier `versions` non ?

2021-04-08 12:33 UTC, sophiemoustard commented on src/components/modals/UpdateAppModal/styles.tsx
> +    fontSize: 20,
pour la gestion des polices dans le design system, tu imagines une autre PR ?

2021-04-08 12:33 UTC, sophiemoustard commented on environment.ts
> +const getEnvVars = () : { baseURL: string } => {
je crois qu'il n'y a pas d'espace avant les :

2021-04-08 12:33 UTC, sophiemoustard commented on src/components/modals/UpdateAppModal/index.tsx
> +const UpdateAppModal = ({ visible } : UpdateAppModalProps) => (
idem ici

2021-04-08 12:33 UTC, sophiemoustard commented
> Dans environment.ts, il considere que l'import des fichiers d'env est un import avec extension. On n'a pas reussi a trouver pourquoi mais on a l'impression que ca vient du fait qu'on a mis environment.ts en typescript.

as tu essaye de mettre les fichiers /env/env.local avec une extension ts ?

2021-04-08 12:40 UTC, cmolle commented on src/components/modals/UpdateAppModal/styles.tsx
> +    fontSize: 20,
Je me disais qu'on pourrait faire une pr pour ajouter tout le design system une fois que Romain nous l'aurait transmis (couleur, font, icones) tu en penses quoi ?

2021-04-09 07:59 UTC, sophiemoustard approved these changes

2021-04-09 08:01 UTC, merged