Com 2048 time stamping screen - format Date for android platform
sophiemoustard/alenvi-erp-mobile pull request #37
Opened 2021-05-10 13:42 UTC by manonpalin

- [x] J'ai testé sur iphone
- [x] J'ai testé sur android

- [x] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [x] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [ ] Je n'ai pas changé de constante -np 

- J'ai ajouté une variable d'environnement : -np
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage : lorsque l'auxiliaire de vie se connecte, il accède a la page horodatage depuis laquelle il voit toutes les interventions du jour. 

Dans cette PR, j'ai modifié l'affichage de la date et de l'heure pour la plateforme android, j'ai ajouté une marge en bas de la page et mis le nom des bénéficiaires en majuscule.

2021-05-10 14:54 UTC, sophiemoustard commented on src/core/helpers/utils.ts
> +    const fullDate = days[day].concat(' ') + date.getDate() + ' '.concat(months[month]);
tu peux formater comme suit en utilisant les ` c'et plus lisible
` const fullDate = `${days[day]} date.getDate() months[month]`;`

2021-05-10 14:56 UTC, sophiemoustard commented on src/core/helpers/utils.ts
> +    const fullDate = days[day].concat(' ') + date.getDate() + ' '.concat(months[month]);
et tu peux retourner directement la valeur sans creer de variable 
`return fullDate = `${days[day]} date.getDate() months[month]`;`

2021-05-10 14:56 UTC, sophiemoustard commented on src/core/helpers/utils.ts
> +  if (Platform.OS === 'android') {
on pourrait faire cette manip quelque soit la plateforme qu'en penses tu ?

2021-05-10 14:58 UTC, sophiemoustard commented on src/core/helpers/utils.ts
> +    return hours.concat(':').concat(minutes);
idem ici tu peux utiliser la \` et les ${}
en fait entre 2 \`, tout ce que tu ecris normalement est interpreté comme une chaine de caractères et ce que tu mets a l'interieur de `${...}` est interpreté comme une variable

2021-05-10 15:13 UTC, manonpalin commented on src/core/helpers/utils.ts
> +    const fullDate = days[day].concat(' ') + date.getDate() + ' '.concat(months[month]);
Oui je suis d'accord! Je viens justement de lire l'article que tu as posté dans veille technique sur les bonnes pratiques dans lequel ils disent d'éviter les concaténations comme j'ai fait !

2021-05-10 16:04 UTC, sophiemoustard commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
pardon je viens de vois en fait si tu le mets ici, on voit la marge tout le temps - et nous on aimerait la voir uniquement quand on est tout en bas du scroll
tu peux du coup creer un nouveau style et le passer en props `contentContainerStyle` dnas la flatList

2021-05-10 16:39 UTC, manonpalin commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
Lorsque je mets la marge sur la flatList, il y a également un espace entre la tabBar et la flatList. J'ai aussi essayé d'ajouter du padding au bas de l'écran mais l'écart entre la flatList et la tabBar est aussi présent

2021-05-10 16:48 UTC, manonpalin commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
Et si je mets le style dans `contentContainerStyle`, aucune marge n'apparait...

2021-05-11 06:44 UTC, sophiemoustard commented on src/screens/TimeStampingProfile/index.tsx
> +
il faut que tu mettes ca dans un useEffect : 
```
useEffect(() => {
  const interval =   setInterval(() => { setCurrentDate(new Date()); }, 60000);
  return clearInterval(interval);
}, []);
```
pour que le compteur disparaisse quand le composant se detruit. sinon ca fait une fuite memoire

2021-05-11 07:06 UTC, sophiemoustard requested changes

2021-05-11 07:06 UTC, sophiemoustard commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
en effet avec la view ca ne fonctionne plus - ca fonctionnait avec la scrollView

2021-05-11 07:06 UTC, sophiemoustard commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
le scroll me perturbe avec la VIew...
on pourrait du coup utiliser map plutot et faire comme suit
`{events.map(ev => renderEvent(ev))}`
avec 
```
const renderEvent = (event: EventType) => (
    <View key={event._id}>
      <TimeStampingCell event={event} />
      <View style={styles.separator} />
    </View>
  );
```
qu'en pensez vous ?

2021-05-11 08:14 UTC, manonpalin commented on src/screens/TimeStampingProfile/styles.ts
> +    marginBottom: MARGIN.MD,
Oui, en effet j'avais pris le problème dans l'autre sens mais remplacer la flatList par le .map permet d'avoir un meilleur rendu visuel sur le scroll

2021-05-11 08:36 UTC, sophiemoustard commented on src/screens/TimeStampingProfile/index.tsx
> +    <ScrollView style={styles.screen} >
tu as un espace en trop

2021-05-11 09:04 UTC, sophiemoustard approved these changes

2021-05-11 11:29 UTC, merged