Com 2073
sophiemoustard/alenvi-erp-mobile pull request #41
Opened 2021-05-12 13:23 UTC by manonpalin

- [x] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [x] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [ ] Je n'envoie pas de nouveau paramètre dans une route -np
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [x] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement : -np
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage : lorsque l'auxiliaire est sur la page `horodatage`, elle peut cliquer sur le bouton `commencer` d'une intervention pour horodater de facon manuelle. La date horodatée ainsi que le nom du bénéficiaire s'affichent. 

La liste des motifs justifiant l'horodatage manuel s'affiche. Cependant je n'ai pas encore trouvé comment créer le radio Button devant chaque motif. J'ouvre donc cette PR, et en ferai une seconde une fois que j'aurais trouvé comment ajouter ces RadioButton :)

2021-05-12 15:56 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +    <View>
Je crois que tu peux mettre uniquement `<>`

2021-05-12 15:56 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/styles.ts
> +    flexGrow: 5,
Est-il utile ?

2021-05-12 16:12 UTC, sophiemoustard requested changes

2021-05-12 16:12 UTC, sophiemoustard commented on src/components/TimeStampingCell/styles.ts
> +    paddingHorizontal: PADDING.XL,
que pensez vous d'homogénéiser le style dans Button pour ca ?

2021-05-12 16:12 UTC, sophiemoustard commented on src/components/TimeStampingCell/styles.ts
> +    marginTop: MARGIN.XS,
a la place, tu pourrais utiliser la propriété `alignItems: 'center',` dans le style `container` pour aligner verticalement tous les enfants de `container` au centre de la div

2021-05-12 16:12 UTC, sophiemoustard commented on src/components/TimeStampingCell/index.tsx
> +          }
je ne me souviens plus du standard dessus donc je vous pose la question : que pensz vous de fermer } sur la ligne du dessus ?

2021-05-12 16:12 UTC, sophiemoustard commented on src/components/radioButtonList/index.tsx
> +    <FlatList data={list} keyExtractor={ item => item.label } style={styles.container}
ici `keyExtractor={ item => item.label }` tu n'as pas besoin d'espace apres { et avant }

2021-05-12 16:12 UTC, sophiemoustard commented on src/screens/timeStamping/ManualTimeStamping/styles.ts
> +    marginTop: MARGIN.XXXL,
peut on gerer l'affichage du bouton sans ca ? avec un flex: 1 sur la view du dessus peut etre ?

2021-05-12 16:12 UTC, sophiemoustard commented on src/screens/timeStamping/ManualTimeStamping/styles.ts
> +    marginLeft: MARGIN.MD,
que pensses tu de mettre `margin: MD` ?

2021-05-14 06:42 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/styles.ts
> +    flexGrow: 5,
Non, du tout,  je l'avais  ajouté pour faire un test et j'ai oublié de le retirer avant de push

2021-05-14 06:44 UTC, manonpalin commented on src/components/radioButtonList/index.tsx
> +  }[],
Oui tu as raison, ce sera plus lisible de créer le style RadiobuttonListType

2021-05-14 06:45 UTC, manonpalin commented on src/components/radioButtonList/index.tsx
> +  <View>
Non vous avez raison, un `<>` suffit

2021-05-14 07:02 UTC, manonpalin commented on src/components/TimeStampingCell/index.tsx
> +    civilities: civility,
Au début, je voulais mettre civility mais vu que la variable civility est déjà utilisée dans le useState, ce n'était pas possible. Et je n'ai pas trouvé de synonyme... 
As-tu une autre idée de nom?

2021-05-14 07:05 UTC, manonpalin commented on src/components/radioButtonList/index.tsx
> +  <View>
Non, bien vu! Ici un `<>` suffit ;)

2021-05-14 07:06 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +          title={'Êtes-vous sûr de cela ?'} contentText={'Vous reviendrez à la page précédente.'} />
Non je n'ai pas validé auprès de Romain, je vais lui écrire pour savoir ce qu'il en pense

2021-05-14 07:18 UTC, manonpalin commented on src/components/TimeStampingCell/index.tsx
> +  const goToManualTimeStamping = () => navigation.navigate('ManualTimeStamping', {
Ah oui bien vu! 
Je me pose une question: est-ce qu'il vaut mieux passer l'id du bénéficiaire en plus de son nom et de sa civilité lors de la navigation ou comme tu l'as dit, seulement passer l'id et refaire un appel a l'api pour accéder a toutes ses informations?

2021-05-14 07:19 UTC, manonpalin commented on src/screens/timeStamping/TimeStampingProfile/index.tsx
> -);
C'est un oubli, je l'avais deplacé pour vérifier quelque chose et j'ai oublie de le replacer! Je modifie

2021-05-14 07:22 UTC, manonpalin commented on src/components/TimeStampingCell/index.tsx
> +          }
Oui bien vu !

2021-05-14 07:37 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +              <Text style={styles.info}>{currentTime.getHours()}:{displayMinutes(currentTime)}</Text>
Mais oui très bien vu, il en existe même déjà une !

2021-05-14 08:47 UTC, cmolle commented on package-lock.json
>          }
Je suis etonnee que le package-lock soit modifie alors qu'il n'y a pas de nouvelles librairies installées. 
Est-ce que tu peux refaire un npm i ? C'est possible qu'il y ait des modifications (si des paquets que l'on utilise ont mis leurs dependances a jour), cependant on ne les commit pas si il n'y a pas de nouvelles librairies dans notre package.json.

2021-05-14 08:47 UTC, cmolle commented on src/components/radioButtonList/index.tsx
> +  options: RadioButtonListType[],
Comme la props s'appelle maintenant option, tu peux renommer le type en RadioButtonOptionsType

2021-05-14 08:47 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +                {CIVILITY_OPTIONS[route.params.event.customer.identity.title]} {}
Pourquoi le `{}` ?

2021-05-14 08:47 UTC, cmolle commented on src/components/radioButtonList/styles.ts
> +import { StyleSheet } from 'react-native';
up

2021-05-14 08:50 UTC, cmolle commented on src/components/TimeStampingCell/styles.ts
> +    paddingHorizontal: PADDING.XL,
up

2021-05-14 08:50 UTC, cmolle commented on src/components/TimeStampingCell/index.tsx
> +  const goToManualTimeStamping = () => navigation.navigate('ManualTimeStamping', {
Vu ensemble : finalement on passe des champs de evenements

2021-05-14 08:53 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +                {route.params.event.customer.identity.lastname.toUpperCase()}
comme ce sont des champs imbriqués, il vaut mieux verifier qu'ils sont bien definis. Il me semble que l'on peut faire quelque chose comme `route.params.event?.customer?.identity?.lastname?.toUpperCase() || ''`

2021-05-14 09:39 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +          title={'Êtes-vous sûr de cela ?'} contentText={'Vous reviendrez à la page précédente.'} />
Romain m'a dit que dans ce cas, rien ne sert d'afficher une modale car cette fonctionnalité sera utilisée très fréquemment et l'ajout de la modale serait plus contraignant qu'autre chose d'un point de vue utilisation.

2021-05-14 09:46 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +                {CIVILITY_OPTIONS[route.params.event.customer.identity.title]} {}
Justement je voulais voir avec toi comment ajouter un espace entre les deux champs que l'on affiche a l'écran. J'ai essaye de désactiver les règles es-lint sur la ligne pour pouvoir y ajouter un espace a la fin mais ca ne fonctionne pas.

2021-05-14 09:46 UTC, manonpalin commented on src/components/radioButtonList/index.tsx
> +  options: RadioButtonListType[],
Bien vu!

2021-05-14 09:48 UTC, manonpalin commented on package-lock.json
>          }
C'est peut être parce que j'ai installé un nouveau package pour gérer l'ajout des checkbox. J'ai stash mes modifs mais n'ai pas fait de `npm i` avant de prendre mes retours.

2021-05-14 10:34 UTC, manonpalin commented on src/components/radioButtonList/styles.ts
> +import { StyleSheet } from 'react-native';
J'ai un soucis, dans mon workspace il est bien renommé avec une majuscule. Si je le renomme `radio...` puis fais git status, aucune modification n'est visible par git puisqu'il n'affiche rien. ( et inversement lorsque je repasse de `radio..` a `Radio...` As-tu déjà rencontre ce probleme? 
<img width="188" alt="Capture d’écran 2021-05-14 à 12 31 47" src="https://user-images.githubusercontent.com/81675019/118258664-78458d80-b4b0-11eb-8c46-d11b90e8ab3a.png">
<img width="357" alt="Capture d’écran 2021-05-14 à 12 32 06" src="https://user-images.githubusercontent.com/81675019/118258670-7a0f5100-b4b0-11eb-9d82-e1f4f597faef.png">

2021-05-14 10:36 UTC, manonpalin commented on package-lock.json
>          }
J'ai bien refait un `npm i ` et j'ai des Maj de package dans package-lock.json.
 Comment puis-je retirer ce fichier de ma pr?

2021-05-14 12:44 UTC, cmolle commented on src/components/RadioButtonList/index.tsx
> +type RadioButtonOptionType = { label: string, value: number };
Tu peux mettre un s a options

2021-05-14 12:44 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +  const lastName = route.params.event?.customer?.identity?.lastname.toUpperCase() || '';
Pour eviter qu'ils ne soient calculer a chaque rendu mais uniquement quand il y en a besoin, on peut faire comme ceci : 
```
const [civility, setCivility] = useState<string>(route.params.event?.customer?.identity?.title || '');
const [lastname, setLastname] = useState<string>(route.params.event?.customer?.identity?.lastname.toUpperCase() || '');

useEffect(() => {
 setCivility(route.params.event?.customer?.identity?.title || '');
 setLastname(route.params.event?.customer?.identity?.lastname.toUpperCase() || '');
}, [route.params.event])
```

2021-05-14 12:44 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +
On doit pouvoir le definir en dehors du composant, comme il ne depend d'aucune variables du composant. Ca permet qu'il ne soit pas recréé à chaque rendu.

2021-05-14 12:44 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +      </View>
Est-ce que tu peux verifier avec Romain qu'on laisse bien la croix et qu'on ne met pas plutot une fleche ici ? Sur l'application formation, il me semble que quand il y a la croix, il y a une modale de verification, et une fleche quand il n'y en a pas.

2021-05-14 15:12 UTC, manonpalin commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +      </View>
Vu avec Romain, dans ce cas on garde bien la croix puisqu'on est dans la situation ou on a entamé une action !

2021-05-14 15:39 UTC, cmolle commented on src/components/RadioButtonList/index.tsx
> +  <>
Je n'ai pas l'impression que ce soit utile

2021-05-14 15:39 UTC, cmolle commented on src/components/RadioButtonList/styles.ts
> +    marginBottom: MARGIN.MD,
Est-il utile ?

2021-05-14 15:39 UTC, cmolle commented on src/components/TimeStampingCell/index.tsx
> +        <View style={styles.view}>
Ici, on pourrait ne plus avoir besoin du `styles.view` en placant du padding dans container. On a tout de meme besoin des view j'ai l'impression. 

je te propose ce code pour la partie jsx: 
```
    <View style={styles.cell}>
      <Text style={styles.title}>{CIVILITY_OPTIONS[civility]} {lastName.toUpperCase()}</Text>
      <View style={styles.sectionDelimiter} />
      <View style={styles.container}>
        <View>
          <Text style={styles.timeTitle}>Début</Text>
          {!!startDate && <Text style={styles.scheduledTime}>{formatTime(startDate)}</Text>}
        </View>
        <View>
          <NiPrimaryButton title='Commencer' onPress={goToManualTimeStamping}/>
        </View>
      </View>
      <View style={styles.sectionDelimiter} />
      <View style={styles.container}>
        <View>
          <Text style={styles.timeTitle}>Fin</Text>
          {!!endDate && <Text style={styles.scheduledTime}>{formatTime(endDate)}</Text>}
        </View>
      </View>
    </View>
```

Ca prepare egalement la partie "fin" pour quand il y aura un bouton pour horodater :)

2021-05-14 15:39 UTC, cmolle commented on src/components/TimeStampingCell/styles.ts
>    },
Si ma suggestion te plait, tu peux ajouter `padding: PADDING.LG` dans le style de container et enlever le style view

2021-05-14 16:25 UTC, manonpalin commented on src/components/TimeStampingCell/index.tsx
> +        <View style={styles.view}>
Oui top! :)

2021-05-14 16:26 UTC, manonpalin commented on src/components/RadioButtonList/index.tsx
> +  <>
Oui il n'est plus utile !

2021-05-14 16:31 UTC, manonpalin commented on src/components/RadioButtonList/styles.ts
> +    marginBottom: MARGIN.MD,
Non bien vu !

2021-05-14 16:44 UTC, cmolle approved these changes

2021-05-17 06:54 UTC, sophiemoustard approved these changes

2021-05-17 06:54 UTC, merged