Com 2046
sophiemoustard/alenvi-erp-mobile pull request #45
Opened 2021-05-18 14:16 UTC by manonpalin

- [ ] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que

- [ ] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas.
- [ ] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement :
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage :

2021-05-19 15:17 UTC, sophiemoustard requested changes

2021-05-19 15:17 UTC, sophiemoustard commented on src/api/Users.ts
> +  }) => {
pour plus de lisibilite2 tu peux définir le type  du user au dessus qu'en penses tu ?

2021-05-19 15:17 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={(text: string) => onChangeIdentity('lastname', text)}/>
tu pourrais definir `onChangeIdentity` comme un fonction qui renvoie une fonction comme suit : 
`const onChangeIdentity = (key: string) => (text: string) => { setEditedUser({...}) };`
et du coup ici tu pourrais simplement mettre `onChangeText={onChangeIdentity('lastname')}`

qu'en penses tu ?

2021-05-19 15:17 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={(text: string) => setEditedUser({ ...editedUser, contact: { phone: formatPhone(text) } })} />
je trouverais ce plus lisible de definir une methode `onChangePhone`

2021-05-19 15:17 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={(text: string) => setEditedUser({ ...editedUser, local: { email: text } })} />
idem ici pour email

2021-05-19 15:23 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={(text: string) => setEditedUser({ ...editedUser, contact: { phone: formatPhone(text) } })} />
ici comme on envoie la donnée au back, il ne faut pas formater le telephone car on veut envoyer l'info sous la forma 0987654321 et non 09 87 65 43 21

2021-05-19 15:24 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +        <Text>{errorMessage}</Text>
je crois qu'on a un composant errorMessage pour afficher le texte de la bonne couleur

2021-05-19 15:45 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={(text: string) => onChangeIdentity('lastname', text)}/>
Oui tu as raison, c'est plus lisible au moment de l'appel

2021-05-19 15:51 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +        <Text>{errorMessage}</Text>
Oui bien vu! J'avais oublié ce composant

2021-05-19 16:05 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  );
tu peux mettre sur une ligne `const onChangePhone = (text: string) => setEditedUser({ ...editedUser, contact: { phone: text } });`

2021-05-19 16:05 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  );
idem

2021-05-19 16:05 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={onChangePhone} />
ca tient sur une ligne

2021-05-19 16:05 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +            onChangeText={onChangeEmail} />
icci aussi

2021-05-19 20:56 UTC, cmolle commented on src/screens/Profile/index.tsx
> +  const goToProfileEdition = () => (navigation.navigate('ProfileEdition'));
Est-ce que les parentheses sont necessaires ?

2021-05-19 20:56 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +      keyboardVerticalOffset={IS_LARGE_SCREEN ? MARGIN.MD : MARGIN.XS} >
Il y a un espace en trop

2021-05-20 06:47 UTC, manonpalin commented on src/screens/Profile/index.tsx
> +  const goToProfileEdition = () => (navigation.navigate('ProfileEdition'));
Non bien vu

2021-05-20 07:30 UTC, sophiemoustard approved these changes

2021-05-20 09:55 UTC, merged