Com 2073 timestamp
sophiemoustard/alenvi-erp-mobile pull request #47
Opened 2021-05-20 07:32 UTC by cmolle

- [ ] J'ai testé sur iphone
- [x] J'ai testé sur android

- [ ] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui parce que
  - Non parce que creation d'une route d'horodatage 

- [ ] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [x] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. - pas encore en prod donc non
- [ ] Je n'ai pas changé de constante

- J'ai ajouté une variable d'environnement : -np
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage : Je peux horodater la date de debut d'un evenement - pour l'instant pour tester il faut aller voir en bdd.

2021-05-20 10:16 UTC, KennyCallegari commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
>            <Text style={styles.question}>Pourquoi horodatez-vous manuellement?</Text>
il manque un petit espace entre 'manuellement' et '?', non ?

2021-05-20 10:19 UTC, sophiemoustard requested changes

2021-05-20 10:19 UTC, sophiemoustard commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +      }
peux tu mettre directement `return setErrorMessage('Merci de selectionner une raison pour l\'horodatage manuel.');` ?

2021-05-20 10:19 UTC, sophiemoustard commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +      if (e.response.status === 409) setErrorMessage('L\'évènement est déja horodaté.');
cote back tu renvoie une 409 s'il y a deja un horodatage ou si l'evenement est en conflit - que penses tu de soit garder la 409 pour les conflits et trouver un autre code pour l'horodatage deja existant OU renvoyer le message d'erreur depuis el back ?

2021-05-20 10:19 UTC, KennyCallegari commented on src/components/RadioButtonList/index.tsx
> +  useEffect(() => setOption(checkedRadioButton), [setOption, checkedRadioButton]);
Pourquoi ne pas le mettre sur le onPressCheckbox ?

2021-05-20 10:20 UTC, KennyCallegari commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +const CAMERA_ERROR = 'camera_error';
Tu ne mets pas ça dans constants ?

2021-05-20 12:43 UTC, cmolle commented on src/screens/timeStamping/ManualTimeStamping/index.tsx
> +      }
Non parce qu'on a une regle eslint "consistent-return" qui du coup m'oblige a avoir un return dans tous les cas ce dont on a pas besoin

2021-05-20 12:44 UTC, cmolle commented on src/components/RadioButtonList/index.tsx
> +  useEffect(() => setOption(checkedRadioButton), [setOption, checkedRadioButton]);
Parce que le setCheckedRadioButton n'estpas synchrone. Du coup si je fais 
```
setCheckedRadioButton(prevValue => (prevValue === value ? null : value))
setOption(checkedRadioButton)
```

Je ne suis pas sure d'avoir la derniere valeur de checkedRadioButton

2021-05-20 14:21 UTC, KennyCallegari approved these changes

2021-05-20 14:46 UTC, KennyCallegari reviewed
On a un petit loading sur le bouton ? Pour bien comprendre qu'il a envoyé la requête ?

2021-05-21 07:15 UTC, sophiemoustard approved these changes

2021-05-21 07:15 UTC, merged