COM-2046 manage errors
sophiemoustard/alenvi-erp-mobile pull request #49
Opened 2021-05-20 15:30 UTC by manonpalin

- [x] J'ai testé sur iphone
- [ ] J'ai testé sur android

- [x] La nouvelle version de l'app est compatible avec l'ancienne version de l'API ? (J'ai teste en me mettant sur
  master en api)
  - Oui 
  - Non parce que

- [x] Je n'envoie pas de nouveau paramètre dans une route
    - Si j'en envoie un nouveau, explication et gestion de la compatibilite:
- [ ] J'attends un nouveau champs en retour de l'api: j'ai géré le cas où il n'y est pas -np
- [ ] J'appelle une nouvelle route: j'ai géré le cas ou la route n'existe pas. -np
- [x] Je n'ai pas changé de constante 

- J'ai ajouté une variable d'environnement : -np
  - [ ] Je l'ai ajouté dans env.dev et env.prod aussi

- Cas d'usage : Lorsque l'utilisateur clique sur "Valider", si l'un des champs n'est pas valide alors un message d'erreur s'affiche sous le champ correspondant. Le message d'erreur disparaît quand l'utilisateur a renseigné du contenu valide pour le champ.

Je viens de relire tout le ticket et il y a une partie de BACK que je n'ai pas faite: 

```
BACK: 

dans authentication : mettre le droit user/edit/{id} à tout le monde

prehandler authorizeuserupdate: si auxiliary_without_company, juste autoriser à modifier nom, prénom, mail, téléphone

```
comment voulez-vous que l'on s'organise? Est-ce qu'on prévoit de la faire en pp demain matin?

2021-05-20 17:39 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +  };
Je pense qu'il vaut mieux creer des state que l'on met a jour dans des useEffect. Ici je pense que les fonctions sont appelées a chaque rendu ce qui n'est pas optimal. 
Si on veut garder le format fonction, on doit pouvoir garder un useMemo, mais je ne sais pas ce qui est le mieux.

2021-05-20 17:39 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +        const userId = await asyncStorage.getUserId();
As-tu besoin de passer par l'asyncStorage ? Comme on a le loggedUser qui vient de contexte, on devrait avoir l'id directement.

2021-05-21 06:30 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +        const userId = await asyncStorage.getUserId();
Oui tu as raison !

2021-05-21 06:52 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +  };
Ah oui bien vu, je vais plutôt créer des States et les mettre a jour dans un useEffect

2021-05-21 07:12 UTC, cmolle reviewed
Sur android, il y a un bouton pour revenir en arriere. Sur les pages ou il y a une modale de confirmation quand on souhaite en sortir, il faut que cette modale s'affiche egalment quand on appuie sur le bouton pour revenir en arriere. Pour cela tu peux faire : 
```
  useEffect(() => {
    BackHandler.addEventListener('hardwareBackPress', onPressExitModal); // indique d'appeler la methode onPressExitModal lorque l'on appuie sur le bouton de retour en arriere sur android 

    return () => { BackHandler.removeEventListener('hardwareBackPress', onPressExitModal); // le lien entre les deux est enlevé lorsque le composant est demonte };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

2021-05-21 07:12 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +      setIsLoading(false);
Pourquoi `setIsLoading(false)` ici ?

2021-05-21 07:12 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +        setIsLoading(true);
Pour que loading se remette bien a false a la suite de cette methode (ex: si l'application renvoie une erreur - tu peux couper le back pour tester - le loader ne s'arrete pas) tu peux mettre : 
```
try {
  // ne rien changer
} catch (e) {
 // idem
} finally { // s'execute dans tous les cas
   setLoading(false)
}
```

2021-05-21 07:25 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
>    const [validation, setValidation] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
Oui je suis d'accord!

2021-05-21 07:28 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +      setIsLoading(false);
Je pensais qu'en mettant loading a false le loader se remettrai bien a jour mais en fait il faut plutôt arrêter le loader âpres l'avoir passé a true comme tu l'a expliqué dans le commentaire suivant

2021-05-21 07:56 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +        setIsLoading(true);
Sur android, je n'ai pas bien compris pourquoi est-ce qu'on ajoute: 
```
useEffect(() => {
    BackHandler.addEventListener('hardwareBackPress', onPressExitModal); // indique d'appeler la methode onPressExitModal lorque l'on appuie sur le bouton de retour en arriere sur android 

    return () => { BackHandler.removeEventListener('hardwareBackPress', onPressExitModal); // le lien entre les deux est enlevé lorsque le composant est demonte };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```
Le fait d'appuyer sur la Croix renvoie bien sur la page Profil si il n'y a pas eu de modifications et affiche bien la modale si l'utilisateur a apporté des modifications

2021-05-21 08:00 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +        setIsLoading(true);
En effet, la croix fonctionne bien. Cependant sur android tu a un bouton en bas a droite qui permet de faire retour arriere. On veut qu'il est le meme comportement que la croix.

2021-05-21 08:02 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +        setIsLoading(true);
Ah oui d'accord! En effet la modale ne s'affiche pas lorsqu'on clique dessus, j'apporte les modifs :)

2021-05-21 09:57 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
tu peux mettre directement `'hardwareBackPress', onPressExitModal` (je crois que c'est le reste d'un test qu'on a fait ensemble ^^)

2021-05-21 12:01 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +    return () => { BackHandler.removeEventListener('hardwareBackPress', () => onPressExitModal()); };
Il faut l'enlever ici aussi le `() => `

2021-05-21 13:40 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +    return () => { BackHandler.removeEventListener('hardwareBackPress', () => onPressExitModal()); };
Mince il m'avait échappé celui ci !

2021-05-21 13:58 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +  }, []);
Peux-tu placer ce useEffect en dessous de onPressExitModal ? COmme le useEffect utilise la fonction, c'est plus lisible si c'est juste en dessous.

2021-05-21 13:58 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +      phone: !editedUser.contact.phone.match(PHONE_REGEX) && editedUser.contact.phone.length > 0,
Le telephone n'est pas forcement defini. J'ai l'impression que les `?` ne fonctionne pas pour le match. Tu peux du coup transformer la condition en `editedUser.contact.phone && (!editedUser.contact.phone.match(PHONE_REGEX) && editedUser.contact.phone.length > 0)`

2021-05-21 13:58 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +      phone: !editedUser.contact.phone.match(PHONE_REGEX) && editedUser.contact.phone.length > 0,
J'ai toujours l'erreur 'telephone non valide' si je supprime le numero de telephone. Par contre si j'appuie sur valider, je pars bien de la page.

2021-05-21 14:52 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +      phone: !editedUser.contact.phone.match(PHONE_REGEX) && editedUser.contact.phone.length > 0,
@chloe tu as l'erreur lorsque tu valides et reviens sur la page édition?

2021-05-21 14:56 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +      phone: !editedUser.contact.phone.match(PHONE_REGEX) && editedUser.contact.phone.length > 0,
Non :) Par contre je crois que si je valide et qu'il y a une erreur sur un autre champs, j'ai toujorus l'erreur sur le telephone (meme si il est maintenant vide

2021-05-21 14:58 UTC, sophiemoustard requested changes

2021-05-21 14:58 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
c'est plutot invalid que unvalid non ?

2021-05-21 14:58 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
a enlever -> si eslint nous remonte l'erreur c'est qu'il y a un probleme sousjacent. Je propose que sauf si on ne sait vraiment pas comment la resoudre, on fait en sorte d'etre reglo de ce cote la. qu'en pensez vous ?

2021-05-21 14:58 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
je pense que ce n'est pas une bonne pratique d'utiliser `any` comme type - autant ne pas utiliser typescript dans ce cas. je vous propose que dans le max des cas on esssaie de bien typer nos variables qu'en pensez vous ?

2021-05-21 15:01 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
Oui bien vu!

2021-05-21 15:01 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
Je suis d'accord. Je me posais la question ici vu que c'est un type derive de celui de user si ca ne vallait pas le coup d'attendre qu'on statut sur comment on gere les types similaires. Qu'en penses-tu ?

2021-05-21 15:04 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
Oui pardon c'est un oubli de pendant des tests tout a l'heure. Si je le retire il n'y a pas d'erreur es-lint

2021-05-21 15:04 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
pour le coup la ca me semble un peu eloigner car on ne part pas de identity.lastname mais bien de lastname et c'st un boolean et non une chaine de caractere...

2021-05-21 15:08 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
Ha oui t'as raison desolee ^^"

2021-05-21 15:32 UTC, manonpalin commented on src/screens/ProfileEdition/index.tsx
> +  const [unvalid, setUnvalid] = useState<any>({ lastName: false, phone: false, email: false, emptyEmail: false });
Je suis aussi d'accord

2021-05-21 15:51 UTC, sophiemoustard commented on src/screens/ProfileEdition/index.tsx
> +    if (invalid.emptyEmail && isValidationAttempted) setEmailError('Ce champ est obligatoire.');
tu peux mettre des else ici pour repasser le message a '' une fois que la personne a corriger

2021-05-24 07:46 UTC, sophiemoustard approved these changes

2021-05-24 10:46 UTC, cmolle commented on src/screens/ProfileEdition/index.tsx
> +        const userId = loggedUser._id;
Pas besoin de definir userId avant

2021-05-24 11:43 UTC, cmolle approved these changes

2021-05-24 11:43 UTC, merged